### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by YRHwang90** [R-Computing-Lab/discord#1]
# Return an abridged output of the discord regression model
abridge <- singleEntered %>%
  # drop NAs only from the columns that we will be using
  # in the specific model
  tidyr::drop_na(contains(modelColumns)) %>%
  # perform the discord regression
  discord::discord_regression(outcome = "h40_sf12_mcs_score_xrnd",
                              predictors = c("edu40", "sample_sex_1979", "sample_race_78scrn", "will_1_2012","log_fam_wealth", "log_fam_income_40"),id="extended_id",
                              sex = NULL,
                              race = NULL,
                              pair_identifiers=c("_s1","_s2"),
                              abridged_output = TRUE)

# print model summary

abridge

in this code, we can only put NULL after sex and race, since otherwise it generates error

**Comment by YRHwang90** [comment]
solution: change the variable names of sex and race into "sex" and "race"

**Comment by smasongarrison** [comment]
When you solve the issue, please close the comment
