### ISSUE TITLE
Discord_data unused arguments error code

### ISSUE THREAD

**Issue by esims96** [R-Computing-Lab/discord#10]
The error is in this section: {r discordmodels}
This code chunk:
data_DEP = discord_data (data = dsSingle_G1,
                      outcome = "DELIN_AVERAGE",
                      predictors=c("CESD_7_1992", "CESD_20_1992", "CESD_7_1994"),
                     doubleentered=F,
                     id=dsSingle_G1$ExtendedID,
                     df=dsSingle_G1,
                     sep="_S",
                     scale=F)
This error:
Error in discord_data(data = dsSingle_G1, outcome = "DELIN_AVERAGE", predictors = "CESD_7_1992",  :
  unused arguments (doubleentered = F, df = dsSingle_G1, sep = "_S", scale = F)

**Comment by jdtrat** [comment]
Hi @esims96, without a reprex it's hard to debug an error, so please consider providing data to do so in the future. You can read more about [reproducible examples here](http://reprex.tidyverse.org/). 

That said, this error suggests you're passing arguments that are no longer accepted into the function `discord_data()`.Try downloading the latest version of discord from GitHub as follows and call the help documentation for examples of how to use the function. 

```r
# install and load latest version of discord
remotes::install_github("R-Computing-Lab/discord")
library(discord)

# call help documentation
?discord_data
```
