### ISSUE TITLE
Could not find function "kinsim"

### ISSUE THREAD

**Issue by Xuanyu-Lyu** [R-Computing-Lab/discord#11]
I wanted to run some simulations for my project, however, after I installed the package, libraryed the package and call the function kinsim(). It seemed that the function was not successfully attached to the package. 

I tried to either install the package from cran or GitHub, but neither of them worked. Other functions like discord_data() and discord_regression() worked normally. 

Thanks in advance for checking that issue.

**Comment by smasongarrison** [comment]
interesting!
